// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package template

import (
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewController(db *gorm.DB) *Controller {
	templateRepository := ProvideRepository(db)
	templateService := ProvideService(templateRepository)
	controller := ProvideController(templateService)
	return controller
}

// wire.go:

var ProviderSet = wire.NewSet(
	ProvideRepository,
	ProvideService,
	ProvideController,
)
